# Generated by Django 3.2.11 on 2022-01-14 15:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="indexpage",
            name="intro",
        ),
    ]
