# Generated by Django 3.2.11 on 2022-01-14 17:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_experiencepage"),
    ]

    operations = [
        migrations.AddField(
            model_name="experiencepage",
            name="code",
            field=models.CharField(default="", max_length=6),
        ),
        migrations.AddField(
            model_name="experiencepage",
            name="cover_img_url",
            field=models.URLField(default=""),
        ),
        migrations.AddField(
            model_name="experiencepage",
            name="description",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="experiencepage",
            name="exp_url",
            field=models.URLField(default=""),
        ),
        migrations.AddField(
            model_name="experiencepage",
            name="name",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="experiencepage",
            name="no_bots",
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name="experiencepage",
            name="no_players",
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name="experiencepage",
            name="vid_url",
            field=models.URLField(default=""),
        ),
    ]
