# Generated by Django 3.2.11 on 2022-01-17 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_delete_experiencesubmitpage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experiencepage',
            name='name',
        ),
        migrations.AlterField(
            model_name='experiencepage',
            name='code',
            field=models.CharField(blank=True, default='', help_text='Six letter alpha-numeric code of you experience', max_length=6),
        ),
        migrations.AlterField(
            model_name='experiencepage',
            name='cover_img_url',
            field=models.URLField(blank=True, default='', help_text='Link for your cover Image'),
        ),
        migrations.AlterField(
            model_name='experiencepage',
            name='description',
            field=models.TextField(default='', help_text='Description of Your experience'),
        ),
        migrations.AlterField(
            model_name='experiencepage',
            name='exp_url',
            field=models.URLField(blank=True, default='', help_text='Url of your experience'),
        ),
        migrations.AlterField(
            model_name='experiencepage',
            name='no_bots',
            field=models.IntegerField(blank=True, default=-1, help_text='Max Number of Bots in your experience'),
        ),
        migrations.AlterField(
            model_name='experiencepage',
            name='no_players',
            field=models.IntegerField(blank=True, default=-1, help_text='Max Number of Human Players in your experience'),
        ),
        migrations.AlterField(
            model_name='experiencepage',
            name='vid_url',
            field=models.URLField(blank=True, default='', help_text='Link to vid showcasing your experience'),
        ),
        migrations.AddConstraint(
            model_name='experiencepage',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('code__isnull', True), ('exp_url__isnull', False)), models.Q(('code__isnull', False), ('exp_url__isnull', True)), _connector='OR'), name='core_experiencepage_code_or_exp_url'),
        ),
    ]
