# Generated by Django 3.2.11 on 2022-01-19 11:16

from django.db import migrations
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_experiencescategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='experiencepage',
            name='categories',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, to='core.ExperiencesCategory'),
        ),
    ]
