# Generated by Django 3.2.11 on 2022-01-27 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20220126_1230'),
    ]

    operations = [
        migrations.AddField(
            model_name='experiencescategory',
            name='bg_color',
            field=models.CharField(blank=True, default='#474c50', max_length=7),
        ),
        migrations.AddField(
            model_name='experiencescategory',
            name='bg_hover_color',
            field=models.CharField(blank=True, default='#474c50', max_length=7),
        ),
        migrations.AddField(
            model_name='experiencescategory',
            name='text_color',
            field=models.CharField(blank=True, default='#000000', max_length=7),
        ),
        migrations.AddField(
            model_name='experiencescategory',
            name='text_hover_color',
            field=models.CharField(blank=True, default='#000000', max_length=7),
        ),
    ]
