# Generated by Django 3.2.12 on 2022-03-03 11:33

import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0022_homepage_cover_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="homepage",
            name="cover_image",
        ),
        migrations.AddField(
            model_name="homepage",
            name="extra_content",
            field=wagtail.core.fields.StreamField(
                [
                    (
                        "heading",
                        wagtail.core.blocks.CharBlock(form_classname="full title"),
                    ),
                    ("cover_image", wagtail.images.blocks.ImageChooserBlock()),
                    ("blog", wagtail.core.blocks.RichTextBlock()),
                ],
                default=False,
                help_text="Custom Content for a page",
            ),
        ),
    ]
