# Generated by Django 3.2.12 on 2022-03-03 11:36

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_auto_20220303_1703'),
    ]

    operations = [
        migrations.AddField(
            model_name='experiencepage',
            name='extra_content',
            field=wagtail.core.fields.StreamField([('heading', wagtail.core.blocks.CharBlock(form_classname='full title')), ('cover_image', wagtail.images.blocks.ImageChooserBlock()), ('blog', wagtail.core.blocks.RichTextBlock())], default=False, help_text='Custom Content for a page'),
        ),
        migrations.AddField(
            model_name='experiencespage',
            name='extra_content',
            field=wagtail.core.fields.StreamField([('heading', wagtail.core.blocks.CharBlock(form_classname='full title')), ('cover_image', wagtail.images.blocks.ImageChooserBlock()), ('blog', wagtail.core.blocks.RichTextBlock())], default=False, help_text='Custom Content for a page'),
        ),
        migrations.AddField(
            model_name='profilepage',
            name='extra_content',
            field=wagtail.core.fields.StreamField([('heading', wagtail.core.blocks.CharBlock(form_classname='full title')), ('cover_image', wagtail.images.blocks.ImageChooserBlock()), ('blog', wagtail.core.blocks.RichTextBlock())], default=False, help_text='Custom Content for a page'),
        ),
    ]
