# Generated by Django 3.2.12 on 2022-03-03 11:47

import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0024_auto_20220303_1706"),
    ]

    operations = [
        migrations.AlterField(
            model_name="experiencepage",
            name="extra_content",
            field=wagtail.core.fields.StreamField(
                [
                    (
                        "heading",
                        wagtail.core.blocks.CharBlock(form_classname="full title"),
                    ),
                    ("cover_image", wagtail.images.blocks.ImageChooserBlock()),
                    ("text", wagtail.core.blocks.RichTextBlock()),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="experiencespage",
            name="extra_content",
            field=wagtail.core.fields.StreamField(
                [
                    (
                        "heading",
                        wagtail.core.blocks.CharBlock(form_classname="full title"),
                    ),
                    ("cover_image", wagtail.images.blocks.ImageChooserBlock()),
                    ("text", wagtail.core.blocks.RichTextBlock()),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="extra_content",
            field=wagtail.core.fields.StreamField(
                [
                    (
                        "heading",
                        wagtail.core.blocks.CharBlock(form_classname="full title"),
                    ),
                    ("cover_image", wagtail.images.blocks.ImageChooserBlock()),
                    ("text", wagtail.core.blocks.RichTextBlock()),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="profilepage",
            name="extra_content",
            field=wagtail.core.fields.StreamField(
                [
                    (
                        "heading",
                        wagtail.core.blocks.CharBlock(form_classname="full title"),
                    ),
                    ("cover_image", wagtail.images.blocks.ImageChooserBlock()),
                    ("text", wagtail.core.blocks.RichTextBlock()),
                ]
            ),
        ),
    ]
