# Generated by Django 3.2.12 on 2022-05-11 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0028_blogpage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="experiencepage",
            name="code",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Six letter alpha-numeric code of you experience",
                max_length=6,
                verbose_name="Experience Code",
            ),
        ),
    ]
