# Generated by Django 3.2.12 on 2022-08-19 11:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0029_alter_experiencepage_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="experiencepage",
            name="first_publish",
            field=models.BooleanField(default=True),
        ),
    ]
