# Generated by Django 3.2.12 on 2022-08-24 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0037_alter_experiencepage_sub_categories"),
    ]

    operations = [
        migrations.AddField(
            model_name="experiencepage",
            name="favorites",
            field=models.IntegerField(default=0, help_text="Number of favorites"),
        ),
    ]
