# Generated by Django 3.2.12 on 2022-08-24 21:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0039_profile"),
    ]

    operations = [
        migrations.RenameField(
            model_name="profile",
            old_name="favorites",
            new_name="liked",
        ),
        migrations.RemoveField(
            model_name="experiencepage",
            name="favorites",
        ),
        migrations.AddField(
            model_name="experiencepage",
            name="likes",
            field=models.IntegerField(default=0, help_text="Number of likes"),
        ),
    ]
