# Generated by Django 3.2.12 on 2022-08-25 12:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0040_auto_20220824_2103"),
    ]

    operations = [
        migrations.AlterField(
            model_name="experiencepage",
            name="cover_img_url",
            field=models.URLField(
                blank=True,
                default="",
                help_text="Link for your cover Image",
                verbose_name="Cover Image Url",
            ),
        ),
    ]
