# Generated by Django 3.2.12 on 2022-08-28 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0043_alter_subcategory_icon"),
    ]

    operations = [
        migrations.AddField(
            model_name="experiencescategory",
            name="visible",
            field=models.BooleanField(
                default=True, help_text="Show Category on home page?"
            ),
        ),
        migrations.AddField(
            model_name="subcategory",
            name="visible",
            field=models.BooleanField(
                default=True, help_text="Show Category on home page?"
            ),
        ),
    ]
