# Generated by Django 3.2.12 on 2022-08-29 22:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0044_auto_20220828_2145"),
    ]

    operations = [
        migrations.AddField(
            model_name="experiencepage",
            name="trending",
            field=models.BooleanField(
                default=False,
                help_text="Is this experience trending?",
                verbose_name="Set Trending",
            ),
        ),
    ]
