# Generated by Django 3.2.12 on 2022-09-01 14:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0046_title"),
    ]

    operations = [
        migrations.DeleteModel(
            name="title",
        ),
    ]
