# Generated by Django 3.2.12 on 2022-09-06 17:35

import modelcluster.fields
from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0047_delete_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="experiencepage",
            name="creators",
            field=modelcluster.fields.ParentalManyToManyField(
                blank=True, help_text="choose creators", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
