# Generated by Django 3.2.12 on 2022-09-19 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0048_experiencepage_creators"),
    ]

    operations = [
        migrations.AddField(
            model_name="experiencepage",
            name="allow_editing",
            field=models.BooleanField(default=False),
        ),
    ]
