# Generated by Django 3.2.12 on 2022-09-23 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0051_delete_availabletags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="experiencepage",
            name="cover_img_url",
            field=models.URLField(
                blank=True,
                default="",
                help_text="Link for your cover Image",
                max_length=1000,
                verbose_name="Cover Image Url",
            ),
        ),
    ]
