# Generated by Django 3.2.12 on 2022-09-30 19:18

import markdownx.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0053_auto_20220924_1721"),
    ]

    operations = [
        migrations.AlterField(
            model_name="experiencepage",
            name="description",
            field=markdownx.models.MarkdownxField(
                default="",
                help_text="Description of Your experience",
                verbose_name="Description",
            ),
        ),
    ]
