# Generated by Django 3.2.12 on 2022-10-01 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0054_alter_experiencepage_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="experiencescategory",
            name="not_ready",
            field=models.BooleanField(
                default=False,
                help_text="If set, Shows Coming soon page for this category",
            ),
        ),
        migrations.AddField(
            model_name="subcategory",
            name="not_ready",
            field=models.BooleanField(
                default=False,
                help_text="If set, Shows Coming soon page for this category",
            ),
        ),
    ]
