# Generated by Django 3.2.12 on 2022-10-03 19:43

import markdownx.models
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0055_auto_20221001_1417"),
    ]

    operations = [
        migrations.AddField(
            model_name="experiencescategory",
            name="description",
            field=markdownx.models.MarkdownxField(
                blank=True,
                help_text="description of this category that is shown on /category/",
            ),
        ),
        migrations.AddField(
            model_name="subcategory",
            name="description",
            field=markdownx.models.MarkdownxField(
                blank=True,
                help_text="description of this category that is shown on /category/",
            ),
        ),
    ]
