# Generated by Django 3.2.12 on 2022-10-03 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0056_auto_20221003_1943"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="hide_username",
            field=models.BooleanField(
                default=False,
                help_text="If set to true hides the username on the website",
            ),
        ),
    ]
