# Generated by Django 3.2.12 on 2022-10-03 20:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0057_profile_hide_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="liked",
            field=models.ManyToManyField(blank=True, to="core.ExperiencePage"),
        ),
    ]
