# Generated by Django 3.2.12 on 2022-10-07 20:22

import modelcluster.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0061_experiencepage_bugged_report"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="experiencepage",
            name="bugged_report",
        ),
        migrations.AddField(
            model_name="experiencepage",
            name="bugged_report",
            field=modelcluster.fields.ParentalManyToManyField(
                blank=True,
                help_text="People who have reported this exp bugged",
                to="core.Profile",
            ),
        ),
    ]
