# Generated by Django 3.2.12 on 2022-10-08 10:01

import modelcluster.fields
from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0063_auto_20221007_2041"),
    ]

    operations = [
        migrations.AlterField(
            model_name="experiencepage",
            name="broken_report",
            field=modelcluster.fields.ParentalManyToManyField(
                blank=True,
                help_text="People who have reported this is exp broken",
                related_name="broken_report",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="experiencepage",
            name="bugged_report",
            field=modelcluster.fields.ParentalManyToManyField(
                blank=True,
                help_text="People who have reported this exp is bugged",
                related_name="bugged_report",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="experiencepage",
            name="xp_farm_report",
            field=modelcluster.fields.ParentalManyToManyField(
                blank=True,
                help_text="People who have reported this is exp an xp farm",
                related_name="xp_farm_report",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
