# Generated by Django 3.2.12 on 2022-10-11 09:50

import wagtail.contrib.routable_page.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wagtailcore", "0077_alter_revision_user"),
        ("wagtailredirects", "0008_add_verbose_name_plural"),
        ("wagtailforms", "0005_alter_formsubmission_form_data"),
        ("core", "0066_eventspage_event"),
    ]

    operations = [
        migrations.CreateModel(
            name="EventModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            bases=(
                wagtail.contrib.routable_page.models.RoutablePageMixin,
                models.Model,
            ),
        ),
        migrations.DeleteModel(
            name="EventsPage",
        ),
    ]
