# Generated by Django 3.2.12 on 2022-10-11 10:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0068_auto_20221011_0957"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="eventmodel",
            name="event_link",
        ),
        migrations.AddField(
            model_name="eventmodel",
            name="event_id",
            field=models.CharField(
                blank=True,
                help_text="ID of the event to show on website",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="eventmodel",
            name="server_id",
            field=models.CharField(
                blank=True,
                default="870246147455877181",
                help_text="ID of the server in which event is taking place",
                max_length=255,
                null=True,
            ),
        ),
    ]
