# Generated by Django 3.2.12 on 2022-10-11 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0070_rename_eventmodel_discordscheduledevents"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="DiscordScheduledEvents",
            new_name="DiscordScheduledEvent",
        ),
    ]
