# Generated by Django 3.2.12 on 2022-10-11 10:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0071_rename_discordscheduledevents_discordscheduledevent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="discordscheduledevent",
            name="event_id",
            field=models.CharField(
                help_text="ID of the event to show on website",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="discordscheduledevent",
            name="name",
            field=models.CharField(
                help_text="Name of the event (only for admin panel)",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="discordscheduledevent",
            name="server_id",
            field=models.CharField(
                blank=True,
                default="870246147455877181",
                help_text="ID of the server in which event is taking place [default: bfportal.gg discord server's id]",
                max_length=255,
                null=True,
            ),
        ),
    ]
