# Generated by Django 3.2.12 on 2022-10-11 11:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0075_auto_20221011_1105"),
    ]

    operations = [
        migrations.AlterField(
            model_name="discordscheduledevent",
            name="event_id",
            field=models.CharField(
                help_text="ID of the event to show on website", max_length=50, null=True
            ),
        ),
    ]
