# Generated by Django 3.2.12 on 2022-10-11 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0076_alter_discordscheduledevent_event_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="discordscheduledevent",
            old_name="name",
            new_name="title",
        ),
    ]
