# Generated by Django 3.2.12 on 2022-10-11 16:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0077_rename_name_discordscheduledevent_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="experiencepage",
            name="liked_by",
            field=models.ManyToManyField(blank=True, to="core.Profile"),
        ),
    ]
