# Generated by Django 4.1.7 on 2023-07-07 21:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0081_profile_is_mock_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="experiencepage",
            name="is_mock",
            field=models.BooleanField(
                default=False, help_text="Is this a mock experience ?"
            ),
        ),
    ]
