# Generated by Django 4.1.7 on 2023-07-09 10:05

import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0082_experiencepage_is_mock"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogpage",
            name="extra_content",
            field=wagtail.fields.StreamField(
                [
                    ("heading", wagtail.blocks.CharBlock(form_classname="full title")),
                    ("cover_image", wagtail.images.blocks.ImageChooserBlock()),
                    ("text", wagtail.blocks.RichTextBlock()),
                    ("raw_html", wagtail.blocks.RawHTMLBlock()),
                ],
                blank=True,
                use_json_field=True,
            ),
        ),
        migrations.AlterField(
            model_name="experiencepage",
            name="extra_content",
            field=wagtail.fields.StreamField(
                [
                    ("heading", wagtail.blocks.CharBlock(form_classname="full title")),
                    ("cover_image", wagtail.images.blocks.ImageChooserBlock()),
                    ("text", wagtail.blocks.RichTextBlock()),
                    ("raw_html", wagtail.blocks.RawHTMLBlock()),
                ],
                blank=True,
                use_json_field=True,
            ),
        ),
        migrations.AlterField(
            model_name="experiencespage",
            name="extra_content",
            field=wagtail.fields.StreamField(
                [
                    ("heading", wagtail.blocks.CharBlock(form_classname="full title")),
                    ("cover_image", wagtail.images.blocks.ImageChooserBlock()),
                    ("text", wagtail.blocks.RichTextBlock()),
                    ("raw_html", wagtail.blocks.RawHTMLBlock()),
                ],
                blank=True,
                use_json_field=True,
            ),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="extra_content",
            field=wagtail.fields.StreamField(
                [
                    ("heading", wagtail.blocks.CharBlock(form_classname="full title")),
                    ("cover_image", wagtail.images.blocks.ImageChooserBlock()),
                    ("text", wagtail.blocks.RichTextBlock()),
                    ("raw_html", wagtail.blocks.RawHTMLBlock()),
                ],
                blank=True,
                use_json_field=True,
            ),
        ),
        migrations.AlterField(
            model_name="profilepage",
            name="extra_content",
            field=wagtail.fields.StreamField(
                [
                    ("heading", wagtail.blocks.CharBlock(form_classname="full title")),
                    ("cover_image", wagtail.images.blocks.ImageChooserBlock()),
                    ("text", wagtail.blocks.RichTextBlock()),
                    ("raw_html", wagtail.blocks.RawHTMLBlock()),
                ],
                blank=True,
                use_json_field=True,
            ),
        ),
    ]
