# Generated by Django 4.2.3 on 2023-07-14 07:16

import core.models.experience
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0083_alter_blogpage_extra_content_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="experiencepage",
            name="is_variant",
            field=models.BooleanField(
                default=False,
                help_text="Is the experience a variant of some other experience?",
            ),
        ),
        migrations.AddField(
            model_name="experiencepage",
            name="variants",
            field=modelcluster.fields.ParentalManyToManyField(
                blank=True,
                help_text="Variants of this experience",
                to="core.experiencepage",
            ),
        ),
    ]
