# Generated by Django 4.2.3 on 2023-07-25 09:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0083_alter_blogpage_extra_content_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="GenericSystemSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("need_login_to_view_profile", models.BooleanField(default=False)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
