# Generated by Django 4.2.3 on 2023-07-14 07:18

import modelcluster.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0084_experiencepage_is_variant_experiencepage_variants"),
    ]

    operations = [
        migrations.AlterField(
            model_name="experiencepage",
            name="variants",
            field=modelcluster.fields.ParentalManyToManyField(
                blank=True,
                help_text="Variants of this experience",
                to="core.experiencepage",
            ),
        ),
    ]
