# Generated by Django 4.2.3 on 2023-07-25 10:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0084_genericsystemsettings"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogpage",
            name="include_in_sitemap",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="experiencepage",
            name="include_in_sitemap",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="experiencespage",
            name="include_in_sitemap",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="homepage",
            name="include_in_sitemap",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="profilepage",
            name="include_in_sitemap",
            field=models.BooleanField(default=True),
        ),
    ]
