# Generated by Django 4.2.4 on 2024-01-12 20:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0085_blogpage_include_in_sitemap_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="experiencepage",
            name="no_bots",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Max Number of Bots in your experience",
                verbose_name="Number Of Bots",
            ),
        ),
        migrations.AlterField(
            model_name="experiencepage",
            name="no_players",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Max Number of Human Players in your experience",
                verbose_name="Number of Human Players",
            ),
        ),
    ]
