# Generated by Django 4.2.4 on 2025-10-20 10:27

import core.helper
import django.db.models.deletion
import wagtail.blocks
import wagtail.contrib.routable_page.models
import wagtail.fields
import wagtail.images.blocks
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wagtailcore", "0089_log_entry_data_json_null_to_object"),
        ("bf6", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BF6HomePage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "extra_content",
                    wagtail.fields.StreamField(
                        [
                            (
                                "heading",
                                wagtail.blocks.CharBlock(form_classname="full title"),
                            ),
                            ("cover_image", wagtail.images.blocks.ImageChooserBlock()),
                            ("text", wagtail.blocks.RichTextBlock()),
                            ("raw_html", wagtail.blocks.RawHTMLBlock()),
                        ],
                        blank=True,
                        use_json_field=True,
                    ),
                ),
                (
                    "meta_title",
                    models.CharField(
                        blank=True,
                        help_text="If set this title is displayed in embeds",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "meta_description",
                    models.TextField(
                        blank=True,
                        help_text="If set this description is displayed in embeds",
                        null=True,
                    ),
                ),
                (
                    "meta_image",
                    models.URLField(
                        blank=True,
                        help_text="If set this image is displayed in embeds. Recommend size 1200x630px",
                        null=True,
                        validators=[core.helper.validate_image_link],
                    ),
                ),
                ("include_in_sitemap", models.BooleanField(default=True)),
            ],
            options={
                "abstract": False,
            },
            bases=(
                wagtail.contrib.routable_page.models.RoutablePageMixin,
                "wagtailcore.page",
            ),
        ),
        migrations.DeleteModel(
            name="HomePage",
        ),
    ]
