# Generated by Django 4.2.4 on 2026-07-01 16:45

import core.helper
import django.db.models.deletion
import embed_video.fields
import markdownx.models
import modelcluster.fields
import wagtail.blocks
import wagtail.contrib.routable_page.models
import wagtail.fields
import wagtail.images.blocks
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0085_blogpage_include_in_sitemap_and_more"),
        ("wagtailsvg", "0005_alter_svg_file"),
        ("wagtailcore", "0089_log_entry_data_json_null_to_object"),
        ("bf6", "0002_bf6homepage_delete_homepage"),
    ]

    operations = [
        migrations.CreateModel(
            name="ScriptsCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "visible",
                    models.BooleanField(
                        default=True, help_text="Show Category on home page?"
                    ),
                ),
                (
                    "selectable_on_form",
                    models.BooleanField(
                        default=True,
                        help_text="Should this Category be selectable in submit form",
                    ),
                ),
                (
                    "not_ready",
                    models.BooleanField(
                        default=False,
                        help_text="If set, Shows Coming soon page for this category",
                    ),
                ),
                (
                    "description",
                    markdownx.models.MarkdownxField(
                        blank=True,
                        help_text="description of this category that is shown on /category/",
                    ),
                ),
                (
                    "meta_title",
                    models.CharField(
                        blank=True,
                        help_text="If set this title is displayed in embeds",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "meta_description",
                    models.TextField(
                        blank=True,
                        help_text="If set this description is displayed in embeds",
                        null=True,
                    ),
                ),
                (
                    "meta_image",
                    models.URLField(
                        blank=True,
                        help_text="If set this image is displayed in embeds. Recommend size 1200x630px",
                        null=True,
                        validators=[core.helper.validate_image_link],
                    ),
                ),
                (
                    "icon",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailsvg.svg",
                    ),
                ),
            ],
            options={
                "verbose_name": "Scripts Category",
                "verbose_name_plural": "Scripts Categories",
            },
        ),
        migrations.CreateModel(
            name="ScriptsListingPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "extra_content",
                    wagtail.fields.StreamField(
                        [
                            (
                                "heading",
                                wagtail.blocks.CharBlock(form_classname="full title"),
                            ),
                            ("cover_image", wagtail.images.blocks.ImageChooserBlock()),
                            ("text", wagtail.blocks.RichTextBlock()),
                            ("raw_html", wagtail.blocks.RawHTMLBlock()),
                        ],
                        blank=True,
                        use_json_field=True,
                    ),
                ),
                (
                    "meta_title",
                    models.CharField(
                        blank=True,
                        help_text="If set this title is displayed in embeds",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "meta_description",
                    models.TextField(
                        blank=True,
                        help_text="If set this description is displayed in embeds",
                        null=True,
                    ),
                ),
                (
                    "meta_image",
                    models.URLField(
                        blank=True,
                        help_text="If set this image is displayed in embeds. Recommend size 1200x630px",
                        null=True,
                        validators=[core.helper.validate_image_link],
                    ),
                ),
                ("include_in_sitemap", models.BooleanField(default=True)),
            ],
            options={
                "abstract": False,
            },
            bases=(
                wagtail.contrib.routable_page.models.RoutablePageMixin,
                "wagtailcore.page",
            ),
        ),
        migrations.CreateModel(
            name="SnippetPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "extra_content",
                    wagtail.fields.StreamField(
                        [
                            (
                                "heading",
                                wagtail.blocks.CharBlock(form_classname="full title"),
                            ),
                            ("cover_image", wagtail.images.blocks.ImageChooserBlock()),
                            ("text", wagtail.blocks.RichTextBlock()),
                            ("raw_html", wagtail.blocks.RawHTMLBlock()),
                        ],
                        blank=True,
                        use_json_field=True,
                    ),
                ),
                (
                    "meta_title",
                    models.CharField(
                        blank=True,
                        help_text="If set this title is displayed in embeds",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "meta_description",
                    models.TextField(
                        blank=True,
                        help_text="If set this description is displayed in embeds",
                        null=True,
                    ),
                ),
                (
                    "meta_image",
                    models.URLField(
                        blank=True,
                        help_text="If set this image is displayed in embeds. Recommend size 1200x630px",
                        null=True,
                        validators=[core.helper.validate_image_link],
                    ),
                ),
                ("include_in_sitemap", models.BooleanField(default=True)),
                (
                    "featured",
                    models.BooleanField(
                        default=False,
                        help_text="make this rules page featured",
                        verbose_name="Set Featured",
                    ),
                ),
                (
                    "trending",
                    models.BooleanField(
                        default=False,
                        help_text="Is this rules trending?",
                        verbose_name="Set Trending",
                    ),
                ),
                (
                    "description",
                    markdownx.models.MarkdownxField(
                        default="",
                        help_text="Description of your script/rule blocks",
                        verbose_name="Description",
                    ),
                ),
                (
                    "vid_url",
                    embed_video.fields.EmbedVideoField(
                        blank=True,
                        default="",
                        help_text="Link to vid showcasing/explaing your Snippet",
                        verbose_name="Video Url",
                    ),
                ),
                ("first_publish", models.BooleanField(default=True)),
                ("allow_editing", models.BooleanField(default=False)),
                (
                    "is_mock",
                    models.BooleanField(
                        default=False, help_text="Is this a mock script?"
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        help_text="Choose Script Type",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="bf6.scriptscategory",
                    ),
                ),
                (
                    "creators",
                    modelcluster.fields.ParentalManyToManyField(
                        blank=True,
                        help_text="choose creators",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("liked_by", models.ManyToManyField(blank=True, to="core.profile")),
            ],
            options={
                "abstract": False,
            },
            bases=(
                wagtail.contrib.routable_page.models.RoutablePageMixin,
                "wagtailcore.page",
            ),
        ),
        migrations.CreateModel(
            name="ScriptsSubCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "visible",
                    models.BooleanField(
                        default=True, help_text="Show Category on home page?"
                    ),
                ),
                (
                    "selectable_on_form",
                    models.BooleanField(
                        default=True,
                        help_text="Should this Category be selectable in submit form",
                    ),
                ),
                (
                    "not_ready",
                    models.BooleanField(
                        default=False,
                        help_text="If set, Shows Coming soon page for this category",
                    ),
                ),
                (
                    "description",
                    markdownx.models.MarkdownxField(
                        blank=True,
                        help_text="description of this category that is shown on /category/",
                    ),
                ),
                (
                    "meta_title",
                    models.CharField(
                        blank=True,
                        help_text="If set this title is displayed in embeds",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "meta_description",
                    models.TextField(
                        blank=True,
                        help_text="If set this description is displayed in embeds",
                        null=True,
                    ),
                ),
                (
                    "meta_image",
                    models.URLField(
                        blank=True,
                        help_text="If set this image is displayed in embeds. Recommend size 1200x630px",
                        null=True,
                        validators=[core.helper.validate_image_link],
                    ),
                ),
                (
                    "icon",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailsvg.svg",
                    ),
                ),
            ],
            options={
                "verbose_name": "Scripts Sub Category",
                "verbose_name_plural": "Scripts Sub Categories",
            },
        ),
    ]
