# Generated by Django 4.2.4 on 2026-07-07 15:06

from django.db import migrations


def create_default_scripts_category(apps, schema_editor):
    script_category = apps.get_model("bf6", "ScriptsCategory")
    categories = [
        "Debug",
        "Logging",
        "Admin & moderation tools",
        "Interface",
        "Math",
        "Win conditions",
        "Event triggers",
        "Rules",
        "AI",
        "Vehicles",
        "Classes",
        "Weapons",
        "Gadgets",
        "Objectives",
        "Inputs",
        "Others",
    ]
    for category in categories:
        script_category.objects.get_or_create(name=category)


class Migration(migrations.Migration):
    dependencies = [
        ("bf6", "0003_scriptscategory_scriptslistingpage_snippetpage_and_more"),
    ]

    operations = [
        migrations.RunPython(create_default_scripts_category),
    ]
