# Generated by Django 4.2.4 on 2026-07-07 21:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bf6", "0004_auto_20260707_1506"),
    ]

    operations = [
        migrations.AddField(
            model_name="snippetpage",
            name="code",
            field=models.TextField(default="", null=True),
        ),
        migrations.AddField(
            model_name="snippetpage",
            name="exp_json",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
